### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by emmad5** [emmad5/Splicewise#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by Carly-Schaaf** [comment]
Hey Emma, this looks great so far. A few things to add when you have time: 

- [x] The main button with logo should link to /
- [x]  Going to a random route /#/oweiniouewbrviuwebv should redirect or display a 404 page (it works for a random route tacked on to /dashboard/ but not for one tacked own to /#/)
- [x]  Should not be able to visit /login or /signup when logged in, should be redirected to /dashboard

**Comment by emmad5** [comment]
Hey Carly! Finished those three issues!

**Comment by Carly-Schaaf** [comment]
Cool! Seems I still am not being redirected to "/dashboard" when I am logged in and I type in /login or /signup. I'm being redirected to a blank page :/

**Comment by emmad5** [comment]
ok I think it is working now.
